services:
  - type: web
    name: playmysong-backend
    env: node
    region: frankfurt
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: playmysong-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_ORIGIN
        value: https://playmysong.web.app
      - key: PORT
        value: 10000

databases:
  - name: playmysong-db
    plan: free
    region: frankfurt
